#!/usr/bin/env python3
"""EXP-000 artefact generator: docs/literature/LITERATURE_MATRIX.csv.

Provenance rule for this file: a cell is filled only from a source actually
retrieved on 2026-09-20. Where a field was not stated in the retrieved text the
cell reads 'unknown' -- NOT 'no'. 'no' means the source explicitly indicated
absence. verification_status records how much of each entry was actually seen.
"""
import csv
import pathlib
from collections import Counter

COLS = ["paper_id", "title", "authors", "year", "venue", "link", "open_source_code",
        "dataset", "testbed", "oran_stack", "ric_type", "attack_types",
        "feature_modalities", "model", "baseline_models", "split_strategy",
        "cross_deployment_evaluation", "latency_evaluation", "p95_latency",
        "p99_latency", "resource_evaluation", "false_alert_evaluation",
        "class_imbalance", "attack_base_rate", "adversarial_evaluation",
        "external_validation", "limitations", "relevance",
        "what_our_project_learns", "potential_gap", "verification_status",
        "verified_on"]

R = []


def add(**kw):
    row = {c: kw.get(c, "unknown") for c in COLS}
    row["verified_on"] = kw.get("verified_on", "2026-09-20")
    R.append(row)


add(paper_id="P01",
    title="Descriptor: 5G Open Radio Access Network Multi-Modal Intrusion Detection Dataset (NetsLab-5GORAN-IDD)",
    authors="Abed Zadeh F.; Civciss A.; Wickrama Arachchilage V. R.; Liyanage M.; Sandeepa C.",
    year="2025", venue="IEEE Data Descriptions",
    link="https://doi.org/10.1109/IEEEDATA.2025.3614167 | https://zenodo.org/records/18923275 | https://doi.org/10.34740/kaggle/ds/7416931",
    open_source_code="dataset only; CC-BY-4.0; 16.85 GB total per the Zenodo API (Benign.zip 5.94GB, DoS.zip 3.47GB, DDOS.zip 3.09GB, BruteForce.zip 3.32GB, Web.zip 0.59GB; Network_Dataset.csv 227.2MB; Network_Dataset.db 210.7MB; Lower_Layer_Data.db 5.4MB). NOTE: the description lists six categories but only five zips are published - Probe.zip is ABSENT",
    dataset="NetsLab-5GORAN-IDD (self)",
    testbed="physical 5G O-RAN testbed, University College Dublin; Dell Precision 7920 O-Cloud edge server; 2 physical UEs",
    oran_stack="OpenAirInterface; 1 O-CU, 2 O-DU, 1 O-RU",
    ric_type="RIC present; DU radio metrics exported over the E2 interface",
    attack_types="Benign; DoS; DDoS; Probe; Brute Force; Web attacks",
    feature_modalities="CU packet/flow (raw .pcap + Zeek conn.log/http.log/files.log) AND DU radio telemetry (22 PHY/MAC metrics per record, .txt)",
    model="n/a (dataset descriptor)", split_strategy="n/a",
    cross_deployment_evaluation="no (single deployment)", latency_evaluation="n/a",
    p95_latency="n/a", p99_latency="n/a", resource_evaluation="n/a",
    false_alert_evaluation="n/a", adversarial_evaluation="n/a", external_validation="n/a",
    limitations="record counts, label column names, per-record time/device identifiers and the CU-DU synchronisation tolerance are not stated on the landing pages; single site; the Probe category is described but no Probe.zip is published",
    relevance="CRITICAL - the only retrieved public corpus pairing CU flow records with DU radio telemetry under attack labels",
    what_our_project_learns="resolves gate A1 via option A1-b: D_A can be a real, citable, CC-BY artefact instead of an unnamed 'O-RAN testbed capture'",
    potential_gap="the descriptor establishes the corpus but performs no deployability evaluation on it",
    verification_status="PARTIAL: Zenodo record and NetsLab page retrieved; descriptor PDF NOT read")

add(paper_id="P02",
    title="5G-NIDD: A Comprehensive Network Intrusion Detection Dataset Generated over 5G Wireless Network",
    authors="Samarakoon S.; Siriwardhana Y.; Porambage P.; Liyanage M.; Chang S.-Y.; Kim J.; Kim J.; Ylianttila M.",
    year="2022", venue="IEEE DataPort (descriptor 2025, IEEE Data Descriptions)",
    link="https://doi.org/10.21227/xtep-hv36 | descriptor https://doi.org/10.1109/IEEEDATA.2025.3592888",
    open_source_code="dataset; raw pcapng published (BS1.zip 2.2GB, BS2.zip 1.45GB); Argus CSV also published",
    dataset="5G-NIDD (self)",
    testbed="5G Test Network (5GTN), University of Oulu, Finland; two base stations",
    oran_stack="not O-RAN; 5G test network", ric_type="none",
    attack_types="DoS (ICMP/UDP/SYN/HTTP flood, Slowrate) and port scans (SYN, TCP connect, UDP)",
    feature_modalities="packet capture -> Argus flow records; NO radio KPIs",
    model="n/a (dataset)", split_strategy="n/a", cross_deployment_evaluation="no",
    latency_evaluation="n/a", p95_latency="n/a", p99_latency="n/a",
    resource_evaluation="n/a", false_alert_evaluation="n/a",
    class_imbalance="attack-majority in the published CSV; the draft assumes ~60.7% attack prevalence, NOT yet verified against the artefact",
    attack_base_rate="not operational - a capture-session prevalence, not a deployment base rate",
    adversarial_evaluation="n/a", external_validation="n/a",
    limitations="licence not stated on the landing page; record counts and class balance not stated there; no radio-layer features; device identity only via src_ip",
    relevance="CRITICAL - D_B, the transfer target",
    what_our_project_learns="raw pcapng exists, so the A3 'one exporter over both corpora' control is feasible on the D_B side",
    potential_gap="widely used as an in-distribution benchmark; rarely used as an unseen deployment",
    verification_status="PARTIAL: IEEE DataPort landing page retrieved; artefact NOT downloaded")

add(paper_id="P03",
    title="Cross-Layer Intrusion Detection in 5G O-RAN: Gains and Limits of Fusing Radio Telemetry with Network Flow Records",
    authors="Fard H.; Komarov I.; Wunder G.", year="2026",
    venue="IEEE International Conference on Cyber Security and Resilience (CSR), Lisbon",
    link="https://arxiv.org/abs/2606.22450", dataset="NetsLab-5GORAN-IDD",
    testbed="uses the UCD corpus (no new testbed)",
    oran_stack="OAI-based (inherited from the corpus)", ric_type="n/a (offline study)",
    attack_types="as per corpus; DoS emphasised in the confusion analysis",
    feature_modalities="DU radio telemetry (1 s aggregation across all UEs active in the DU, cumulative byte counters first-differenced to per-second rates, remaining KPIs as mean and sd per window -> 44 features) and CU Zeek flow records (conn.log, http.log, files.log; per-window sum/mean/sd with log transform on skewed features -> 68-72 features). Sliding windows W in {5,10} s, stride 2 s",
    model="seven architectures: Logistic Regression, XGBoost, Random Forest, GRU, Temporal Convolutional Network, Transformer, Residual MLP. Hyperparameters tuned on one seed at W=10 then FROZEN across all evaluations",
    baseline_models="single-modality variants of the same architectures",
    split_strategy="run-disjoint over 42 runs; all windows from a run go to exactly one partition; ~70/15/15 by run count, stratified by attack family with at least one run per family per partition; ten seeds giving 19-26 train / 7-12 val / 8-12 test runs",
    cross_deployment_evaluation="no - single corpus, single deployment",
    latency_evaluation="no", p95_latency="no", p99_latency="no", resource_evaluation="no",
    false_alert_evaluation="partial - reports a 1% FPR operating point, but no alert volume and no base-rate sweep",
    attack_base_rate="no", adversarial_evaluation="no", external_validation="no",
    limitations="DoS-to-Benign confusion of 27-46% (mean ~37%) persists across all 42 tested configurations and is near-identical for network (37.6%), radio (37.5%) and fusion (37.3%) on XGBoost, which the authors attribute to windowed statistical aggregation rather than model capacity. Stacked fusion is UNSTABLE at this sample size: ROC-AUC sd +/-0.171 to 0.182 for TCN and Transformer, which they attribute to leakage sensitivity at 42 runs. They state NetsLab-5GORAN-IDD is the only public O-RAN corpus with paired CU flow records and DU radio telemetry, and that confirming transfer beyond this testbed needs new paired captures from independent deployments",
    relevance="CRITICAL - nearest prior work on our D_A; sets the in-distribution reference and constrains our novelty",
    what_our_project_learns="(i) run-disjoint splitting on this corpus is the established protocol, so a random split would be indefensible; (ii) radio beats flow IN-DISTRIBUTION by 8.5-11.7 ROC-AUC points (radio 0.925-0.961 vs network 0.827-0.851) - the first half of our H4 sign-flip is now prior work with numbers attached; (iii) DECISIVE FOR OUR D-008: they align the two modalities by RUN-RELATIVE timestamps from the RAW per-category archives, not the published summary CSV, and for DoS traces lacking telemetry timestamps they assign time from the sample index at 1 Hz. This is an existence proof that our route (a) works, and it supplies the method; (iv) they had only 42 runs and report fusion instability (ROC-AUC sd up to 0.182) at that size, so our own small-sample warning is corroborated by prior work; (v) their authors explicitly name cross-testbed transfer as the open question - which is exactly our RQ1",
    potential_gap="fusion gains measured in-distribution only. Cross-deployment transfer, tail latency, resource cost, alert burden, calibration and robustness are all absent, and the authors name cross-testbed transfer as the stated open question. The second half of our H4 (radio features HURT transfer) is untested by anyone",
    verification_status="GOOD: arXiv full text (HTML) read 2026-09-20. Method, splits, feature counts, headline numbers and limitations all extracted from the paper")

add(paper_id="P04",
    title="Enabling Real-Time AI in O-RAN: Deploying and Measuring AI Inside a Near-RT RIC xApp",
    authors="Obiuwevwi L.; Rechowicz K. J.; Jayarathna S.; Bouk S. H.; Afrin F.; Barati C. N.; Moghim N.; Nanou V.; Rahman M. E.; Shetty S.",
    year="2026", venue="IEEE ICCCN", link="https://arxiv.org/abs/2607.01583",
    dataset="synthetic network-state dataset", testbed="commodity hardware",
    oran_stack="OpenAirInterface", ric_type="FlexRIC (real Near-RT RIC, model embedded in the xApp)",
    attack_types="none - network-state classification, not intrusion detection",
    feature_modalities="cross-layer RAN state: MAC, RLC, PDCP, GTP, UE count",
    model="logistic regression and shallow MLP exported as deterministic C inference modules, no external ML runtime",
    baseline_models="the two models compared against each other", split_strategy="unknown",
    cross_deployment_evaluation="no",
    latency_evaluation="yes - inference-only 1-5 us (LR) and 10-25 us (MLP); end-to-end below 4 ms; CDF characterisation plus a noise ablation",
    p95_latency="yes - more than 95% of projected loop executions within the 10 ms budget",
    p99_latency="not reported", resource_evaluation="no CPU/RAM reported",
    false_alert_evaluation="no", attack_base_rate="no", adversarial_evaluation="no",
    external_validation="no",
    limitations="the authors state the work validates embedding and execution feasibility rather than production-level generalisation; accuracy only 0.88-0.90; synthetic data",
    relevance="CRITICAL - the strongest existing latency comparator, and it assumes the same B = 10 ms budget we do",
    what_our_project_learns="(i) our 10 ms budget has independent precedent; (ii) a C-exported linear model runs orders of magnitude faster than our assumed per-decision cost, so our latency finding must concern the FULL pipeline (feature construction and serialisation), not inference, or it is already answered; (iii) they report p95 but NOT p99, so the tail is still open",
    potential_gap="no p99, no CPU/RAM, no throughput sweep, no real attack data, no detection-quality/latency trade-off",
    verification_status="PARTIAL: arXiv abstract page retrieved; full text NOT read")

add(paper_id="P05",
    title="Performance Analysis of an AI-Based IDS xApp for Cyberattack Anomaly Detection in O-RAN Near-RT RIC",
    authors="NOT VERIFIED", year="2026",
    venue="ScienceDirect (Tech Science Press host), article S152614922600202X",
    link="https://www.sciencedirect.com/org/science/article/pii/S152614922600202X",
    dataset="NetsLab-5GORAN-IDD (O-CU network layer plus O-DU radio telemetry)",
    ric_type="deployed in a Near-RT RIC environment (claimed)",
    attack_types="as per corpus",
    feature_modalities="O-CU network layer and O-DU radio telemetry",
    model="LSTM, CNN, Transformer, Autoencoder. In-distribution F1: CNN 0.9974, Transformer 0.9966, LSTM 0.9949, Autoencoder 0.9644. A structurally optimised LSTM is selected on the performance/efficiency balance",
    split_strategy="unknown", cross_deployment_evaluation="no",
    latency_evaluation="yes - peak inference ~600 ms (LSTM, CNN) and ~850 ms (Autoencoder); LSTM, CNN and Autoencoder all stay within 1000 ms at the maximum load of 80,000 instances on both datasets",
    false_alert_evaluation="unknown", attack_base_rate="unknown",
    p99_latency="YES - approximately 140 ms at p99 for the selected LSTM. This CONTRADICTS the EXP-000 gap claim that no retrieved O-RAN IDS study reports p99. Note 140 ms is 14x a 10 ms budget and 0.14x a 1000 ms budget, so the same measurement passes or fails depending only on which end of the O-RAN near-RT range is chosen",
    adversarial_evaluation="unknown", external_validation="no - but they do compare O-CU against O-DU as two datasets and report the Autoencoder degrading between them (F1 0.9644 -> 0.9115, precision 0.9688 -> 0.8477). That is a cross-LAYER comparison within one deployment, not cross-deployment transfer",
    limitations="assumes a 1000 ms near-RT budget, the permissive end of the 10 ms - 1 s range; F1 94.87% (O-CU) and 99.49% (O-DU) are in-distribution only",
    relevance="HIGH - a second latency comparator on the same corpus, reaching the OPPOSITE deployability verdict to P04 purely by choosing a different budget",
    what_our_project_learns="I11 is now quantified rather than argued. Their selected LSTM has p99 ~140 ms. Against B = 1000 ms it passes comfortably; against our B = 10 ms it fails by 14x. One measurement, two opposite verdicts, decided entirely by which end of the O-RAN 10 ms - 1 s range the author picks. Sweeping B and reporting the crossing point is therefore not a hedge, it is the only way to make the verdict a measurement",
    potential_gap="single budget value at the permissive end; no cross-deployment evaluation; no CPU/RAM; no alert burden at a realistic base rate; in-distribution F1 above 0.99 with no transfer test is exactly the reporting pattern our paper critiques",
    verification_status="MODERATE: publisher still returns HTTP 403; fields come from two independent detailed search-result snippets (2026-09-20) that agree. Numbers are usable for internal reasoning but the PDF MUST be obtained before any of them is cited in the manuscript. Author list still NOT VERIFIED")

add(paper_id="P06", title="ARGOS: Anomaly Recognition and Guarding through O-RAN Sensing",
    authors="Dimou S.; Noubir G.", year="2025", venue="arXiv (cs.NI, cs.CR)",
    link="https://arxiv.org/abs/2506.06916", dataset="own measurement dataset",
    testbed="Open5GS + srsRAN, COTS UEs, shielded anechoic chamber",
    oran_stack="srsRAN", ric_type="FlexRIC (Near-RT RIC)",
    attack_types="Rogue Base Station downgrade attacks",
    feature_modalities="extended KPM service model; cross-layer features from COTS UE Modem Layer 1 (ML1) logs and Measurement Reports",
    model="Variational Autoencoder and other unsupervised anomaly detectors",
    split_strategy="unknown", cross_deployment_evaluation="no",
    latency_evaluation="claims minimal system overhead; no values in the retrieved abstract",
    resource_evaluation="claimed minimal, unquantified in the abstract",
    false_alert_evaluation="partial - 0.6% false positives reported, but no alert volume at a deployment flow rate",
    attack_base_rate="no", adversarial_evaluation="no", external_validation="no",
    limitations="not stated in the abstract; single attack family; RF confined to a chamber",
    relevance="HIGH - the richest UE-level telemetry of any retrieved O-RAN IDS, and the model for what real RIC integration should mean",
    what_our_project_learns="99.5% accuracy at 0.6% FPR still implies a large absolute alert count once multiplied by a deployment flow rate, which directly motivates our Criterion 2",
    potential_gap="overhead asserted rather than quantified; no tail latency; no transfer evaluation",
    verification_status="PARTIAL: arXiv abstract page retrieved; full text NOT read")

add(paper_id="P07",
    title="ZTRAN: Prototyping Zero Trust Security xApps for Open Radio Access Network Deployments",
    authors="Abdalla A. S.; Moore J.; Adhikari N.; Marojevic V.", year="2024",
    venue="IEEE Wireless Communications Magazine", link="https://arxiv.org/abs/2403.04113",
    dataset="none (prototype)", testbed="Open AI Cellular (OAIC) research platform",
    oran_stack="OAIC", ric_type="O-RAN Alliance containerised Near-RT RIC",
    attack_types="unspecified in the abstract",
    model="microservice-based intrusion detection; ML explicitly listed as FUTURE work",
    baseline_models="none", split_strategy="n/a", cross_deployment_evaluation="no",
    latency_evaluation="yes, but user-plane throughput and latency rather than per-decision detector latency",
    p95_latency="no", p99_latency="no", false_alert_evaluation="no",
    class_imbalance="n/a", attack_base_rate="no", adversarial_evaluation="no",
    external_validation="no",
    limitations="the authors state that ML integration and threat-intelligence feeds remain future work; prototype-level",
    relevance="MEDIUM - architectural reference for xApp-encapsulated security functions",
    what_our_project_learns="the xApp containerisation pattern, and the distinction between user-plane latency and decision latency",
    potential_gap="no learned detector, therefore no detection-quality or deployability measurement",
    verification_status="PARTIAL: arXiv abstract page retrieved; full text NOT read")

add(paper_id="P08",
    title="5G-SPECTOR: An O-RAN Compliant Layer-3 Cellular Attack Detection Service",
    authors="Wen H.; Porras P.; Yegneswaran V.; Gehani A.; Lin Z.", year="2024",
    venue="NDSS Symposium (31st)",
    link="https://doi.org/10.14722/ndss.2024.24527 | https://github.com/5GSEC/5G-Spector",
    open_source_code="yes - github.com/5GSEC/5G-Spector", dataset="own testbed traces",
    testbed="O-RAN compliant softwarised 5G",
    oran_stack="OAI-based (per the 5GSEC tooling)",
    ric_type="Near-RT RIC xApp (MOBIEXPERT)",
    attack_types="seven types of layer-3 (RRC/NAS) cellular attacks",
    feature_modalities="MOBIFLOW security audit stream: encoded RRC/NAS messages, UE identifiers and state",
    model="programmable rule/signature-based control-plane xApp (MOBIEXPERT)",
    split_strategy="n/a (not a learned classifier)", cross_deployment_evaluation="no",
    latency_evaluation="claims real-time detection; values NOT retrieved",
    class_imbalance="n/a", attack_base_rate="no", adversarial_evaluation="no",
    external_validation="no",
    limitations="layer-3 control plane only; not a user-plane or IoT-traffic IDS",
    relevance="MEDIUM-HIGH - the reference open-source O-RAN security xApp; defines the telemetry-plus-xApp pattern",
    what_our_project_learns="MOBIFLOW shows that useful security telemetry may require a custom service model rather than stock E2SM-KPM, which bears on our feature-availability assumption",
    potential_gap="rule-based, so no generalisation question; complements rather than competes with our ML deployability study",
    verification_status="WEAK: NDSS PDF could not be parsed; fields from NDSS and search metadata. Re-verify before citation")

add(paper_id="P09",
    title="6G-XSec: Explainable Edge Security for Emerging OpenRAN Architectures (with the MobiWatch xApp)",
    authors="5GSEC group - author list NOT verified", year="2024", venue="ACM HotNets",
    link="https://conferences.sigcomm.org/hotnets/2024/papers/hotnets24-198.pdf | https://github.com/5GSEC/MobiWatch",
    open_source_code="yes - github.com/5GSEC/MobiWatch", dataset="own testbed traces",
    testbed="OpenAirInterface-based O-RAN",
    oran_stack="OpenAirInterface augmented with MobiFlow telemetry",
    ric_type="O-RAN compliant Near-RT RIC xApp",
    attack_types="layer-3 RRC/NAS anomalies; BTS resource depletion",
    feature_modalities="MobiFlow security telemetry (RRC/NAS message sequences, UE state)",
    model="unsupervised deep learning: Autoencoder (MobiWatch-1) and LSTM (MobiWatch-2), plus an LLM xApp for explanation",
    split_strategy="unknown", cross_deployment_evaluation="no",
    attack_base_rate="no", adversarial_evaluation="no", external_validation="no",
    limitations="HotNets workshop scope; control-plane focus",
    relevance="HIGH - the open-source reference implementation of a deep-learning O-RAN security xApp",
    what_our_project_learns="a concrete, runnable xApp skeleton for Track C, which lowers the risk that our RIC integration is bespoke",
    potential_gap="no deployability evaluation in the three-criterion sense",
    verification_status="WEAK: GitHub README and search metadata only; HotNets PDF NOT read")

add(paper_id="P10",
    title="Towards a Multi-Layer Defence Framework for Securing Near-Real-Time Operations in Open RAN",
    authors="Alimohammadi H.; Mayhoub S.; Chatzimiltis S.; Shojafar M.; Bhutta M. N. M.",
    year="2025", venue="IEEE Open Journal of the Communications Society (OJCOMS)",
    link="https://arxiv.org/abs/2512.01596",
    testbed="FlexRIC plus commercial RAN emulator components",
    oran_stack="FlexRIC + commercial emulator", ric_type="Near-RT RIC",
    attack_types="three runtime classes: message-level, data-level (telemetry poisoning) and control-logic-level (malicious xApp)",
    feature_modalities="E2 signalling messages; telemetry time series",
    model="signature-based E2 message inspection; LSTM temporal anomaly scoring; hash challenge-response xApp attestation",
    split_strategy="unknown", cross_deployment_evaluation="no",
    latency_evaluation="yes - under 80 ms total overhead for a network with 500 UEs",
    p95_latency="unknown", p99_latency="unknown",
    resource_evaluation="partial (overhead only)", attack_base_rate="no",
    adversarial_evaluation="partial - poisoning is in the threat model", external_validation="no",
    limitations="overhead reported as a single aggregate rather than a distribution; emulated RAN",
    relevance="HIGH - the best retrieved source for widening our threat model beyond flow classification",
    what_our_project_learns="our threat model (paper Section III) currently covers only data-plane attack traffic; message-level and control-logic threats exist and should at minimum be scoped out explicitly",
    potential_gap="aggregate overhead with no tail; no detection-quality or transfer analysis",
    verification_status="PARTIAL: arXiv abstract page retrieved; full text NOT read")

add(paper_id="P11",
    title="Black-Box Evasion Attacks on Data-Driven Open RAN Apps: Tailored Design and Experimental Evaluation",
    authors="Gajjar P.; Khoja M.; Ganiyu A.; Juarez M.; Marina M. K.; Lehane A.; Shah V. K.",
    year="2025", venue="arXiv", link="https://arxiv.org/abs/2510.18160",
    dataset="testbed and emulation data", testbed="real-world O-RAN testbed plus emulation",
    ric_type="both Near-RT (xApp) and Non-RT (rApp)",
    attack_types="adversarial evasion against ML apps: an interference-classification xApp and a power-saving rApp",
    feature_modalities="RAN data exposed to third-party apps through the RICs",
    model="victim apps are the targets; the attack uses model cloning, input-specific perturbations, universal adversarial perturbations and targeted UAPs",
    baseline_models="n/a", split_strategy="n/a", cross_deployment_evaluation="no",
    latency_evaluation="attacks are designed to respect stringent timing constraints; victim latency is not the metric",
    p95_latency="no", p99_latency="no", false_alert_evaluation="no",
    class_imbalance="n/a", attack_base_rate="n/a",
    adversarial_evaluation="yes - this is the adversarial study, and it succeeds against prominent adversarial-ML defences",
    external_validation="no",
    limitations="the victim apps are not IDS; attack success rates were not retrieved from the abstract",
    relevance="HIGH - direct evidence that clean-test accuracy does not establish O-RAN ML deployability",
    what_our_project_learns="a Phase 8 evasion study on our detector is warranted and has an established methodology to follow (black-box, timing-constrained, UAP)",
    potential_gap="no IDS victim; no measurement of how evasion interacts with alert burden or transfer degradation",
    verification_status="PARTIAL: arXiv abstract page retrieved; full text NOT read")

add(paper_id="P12",
    title="Robust Anomaly Detection in O-RAN: Leveraging LLMs against Data Manipulation Attacks",
    authors="NOT VERIFIED", year="2025", venue="1st free5GC World Forum (ACM)",
    link="https://doi.org/10.1145/3733814.3765495 | https://arxiv.org/abs/2508.08029",
    ric_type="Near-RT RIC (Shared Data Layer attack surface)",
    attack_types="data manipulation by a malicious xApp writing to the Shared Data Layer; 'hypoglyph' Unicode perturbation",
    feature_modalities="SDL-stored telemetry",
    model="LLM-based anomaly detection compared against an AutoEncoder baseline",
    baseline_models="AutoEncoder, which crashes on hypoglyphed input", split_strategy="unknown",
    cross_deployment_evaluation="no",
    latency_evaluation="yes - detection latency below 0.07 s claimed",
    attack_base_rate="no",
    adversarial_evaluation="yes - input manipulation against the detector itself",
    external_validation="no",
    limitations="0.07 s is seven times our 10 ms budget and near the permissive end of the near-RT range; the attack is text/Unicode specific",
    relevance="MEDIUM-HIGH - shows the detector input path is itself an attack surface",
    what_our_project_learns="Phase 8 should include malformed and manipulated telemetry, not only feature-space perturbation; also that an LLM detector is not near-RT at the strict end of the range",
    potential_gap="single attack modality; no transfer or alert-burden analysis",
    verification_status="WEAK: search snippets and DOI metadata only")

add(paper_id="P13", title="The Base-Rate Fallacy and the Difficulty of Intrusion Detection",
    authors="Axelsson S.", year="2000",
    venue="ACM Transactions on Information and System Security (TISSEC) 3(3)",
    link="https://doi.org/10.1145/357830.357849", open_source_code="n/a", dataset="n/a",
    testbed="n/a", oran_stack="n/a", ric_type="n/a", attack_types="n/a",
    feature_modalities="n/a",
    model="Bayesian analysis of detection rate against false alarm rate",
    baseline_models="n/a", split_strategy="n/a", cross_deployment_evaluation="n/a",
    latency_evaluation="n/a", p95_latency="n/a", p99_latency="n/a", resource_evaluation="n/a",
    false_alert_evaluation="yes - the foundational result that the false alarm rate is the limiting factor on the Bayesian detection rate P(Intrusion|Alarm)",
    class_imbalance="yes - the central subject", attack_base_rate="yes - the central subject",
    adversarial_evaluation="n/a", external_validation="n/a",
    limitations="analytical, and pre-dates modern ML-based IDS",
    relevance="CRITICAL - the theoretical basis for our Criterion 2 and equation (5)",
    what_our_project_learns="our PPV-at-realistic-pi argument restates a result that has been known for 26 years, so the novelty cannot be the fallacy itself, only its quantification for a specific O-RAN artefact under measured transfer degradation",
    potential_gap="not a gap but a foundation; cite it to frame, never to claim",
    verification_status="canonical reference; DOI and venue confirmed by search; full text not re-read")

add(paper_id="P14",
    title="Cross-Domain Generalization Failure in Lightweight Intrusion Detection Models for IIoT Networks",
    authors="Hakim M. A.; Uddin M. S.; Anis T. I.", year="2026", venue="arXiv",
    link="https://arxiv.org/abs/2607.00553",
    dataset="three IIoT datasets (names not stated in the abstract)",
    testbed="n/a (public corpora)", oran_stack="none - IIoT, not O-RAN", ric_type="none",
    attack_types="IIoT attacks (unspecified in the abstract)",
    feature_modalities="a shared feature representation restricted to attributes available across all three corpora",
    model="four lightweight architectures", baseline_models="within-domain performance",
    split_strategy="train on one network, evaluate on two others without retraining",
    cross_deployment_evaluation="yes - this is the study",
    latency_evaluation="no", p95_latency="no", p99_latency="no", resource_evaluation="no",
    false_alert_evaluation="partial",
    class_imbalance="yes - evaluates under naturally imbalanced distributions",
    attack_base_rate="partial - shows the evaluation protocol can REVERSE which target appears harder",
    adversarial_evaluation="no", external_validation="yes by construction",
    limitations="no deployability, latency or resource dimension; IIoT rather than O-RAN",
    relevance="HIGH - the closest methodological twin outside O-RAN, and a direct constraint on the novelty of our RQ1",
    what_our_project_learns="(i) the shared-feature-space protocol we plan is the established one; (ii) their finding that the evaluation protocol can reverse the apparent ranking is a warning we must test for rather than assume away; (iii) cross-domain IDS failure is NOT novel in general, so our novelty must rest on the O-RAN deployment context plus the joint criteria",
    potential_gap="no O-RAN, no radio modality, no latency or resource measurement, no RIC",
    verification_status="PARTIAL: arXiv abstract page retrieved; full text NOT read")

add(paper_id="P15",
    title="StormShield: Fingerprint-Based Detection and Mitigation of RRC Signaling Storms in O-RAN 5G RANs",
    authors="NOT VERIFIED", year="2026", venue="arXiv", link="https://arxiv.org/abs/2605.14032",
    attack_types="RRC signalling storms", feature_modalities="RRC signalling fingerprints",
    model="fingerprint-based detection",
    relevance="MEDIUM - the signalling-storm threat is our paper's stated IoT motivation",
    what_our_project_learns="a candidate source for the 'compromised IoT causes signalling overload' claim in our Introduction, which is currently uncited",
    limitations="not assessed", potential_gap="not assessed",
    verification_status="TITLE AND URL ONLY - not retrieved")

add(paper_id="P16",
    title="ORAN-DEFEND: Subspace Detection and Sanitization of Backdoor DRL xApps in Open RAN",
    authors="NOT VERIFIED", year="2026", venue="arXiv", link="https://arxiv.org/abs/2607.06647",
    ric_type="Near-RT RIC", attack_types="backdoored DRL xApps",
    model="subspace detection and sanitisation", adversarial_evaluation="yes (backdoor/poisoning)",
    relevance="MEDIUM - a poisoning-defence precedent for Phase 8",
    what_our_project_learns="poisoning of xApp models is an active 2026 topic, so our Phase 8 label-poisoning experiment has precedent",
    limitations="not assessed", potential_gap="not assessed",
    verification_status="TITLE AND URL ONLY - not retrieved")

add(paper_id="P17",
    title="Rogue Cell: Adversarial Attack and Defense in Untrusted O-RAN Setup Exploiting the Traffic Steering xApp",
    authors="NOT VERIFIED", year="2025", venue="arXiv", link="https://arxiv.org/abs/2505.01816",
    ric_type="Near-RT RIC", attack_types="adversarial attack on a traffic-steering xApp",
    adversarial_evaluation="yes", relevance="MEDIUM - untrusted-xApp threat model",
    what_our_project_learns="threat-model breadth for Section III", limitations="not assessed",
    potential_gap="not assessed", verification_status="TITLE AND URL ONLY - not retrieved")

add(paper_id="P18",
    title="Machine Learning-based Early Attack Detection Using Open RAN Intelligent Controller",
    authors="NOT VERIFIED", year="2023", venue="arXiv", link="https://arxiv.org/abs/2302.01864",
    ric_type="RIC",
    relevance="MEDIUM - an early RIC-based detection precedent for related work",
    what_our_project_learns="establishes the 'high in-distribution accuracy' reporting practice our paper critiques",
    limitations="not assessed", potential_gap="not assessed",
    verification_status="TITLE AND URL ONLY - not retrieved")

add(paper_id="P19", title="Base-Rate Fallacy Redux and a Deep Dive Review in Cybersecurity",
    authors="NOT VERIFIED", year="2022", venue="arXiv", link="https://arxiv.org/abs/2203.08801",
    open_source_code="n/a", dataset="n/a", testbed="n/a", oran_stack="n/a", ric_type="n/a",
    attack_types="n/a", feature_modalities="n/a", model="review", baseline_models="n/a",
    split_strategy="n/a", cross_deployment_evaluation="n/a", latency_evaluation="n/a",
    p95_latency="n/a", p99_latency="n/a", resource_evaluation="n/a",
    false_alert_evaluation="yes", class_imbalance="yes", attack_base_rate="yes",
    adversarial_evaluation="n/a", external_validation="n/a", limitations="review",
    relevance="MEDIUM - a modern restatement of P13 for the Criterion 2 framing",
    what_our_project_learns="a current citation for base-rate reasoning alongside Axelsson",
    potential_gap="n/a", verification_status="TITLE AND URL ONLY - not retrieved")

add(paper_id="P20",
    title="Introducing a Comprehensive, Continuous, and Collaborative Survey of Intrusion Detection Datasets",
    authors="NOT VERIFIED", year="2024", venue="arXiv", link="https://arxiv.org/abs/2408.02521",
    dataset="survey of IDS datasets", testbed="n/a", oran_stack="n/a", ric_type="n/a",
    attack_types="n/a", feature_modalities="n/a", model="n/a", limitations="survey",
    relevance="MEDIUM - a systematic source for Phase 13 external-validation corpus selection",
    what_our_project_learns="use it to select a genuinely independent third corpus rather than another split of D_A or D_B",
    potential_gap="n/a", verification_status="TITLE AND URL ONLY - not retrieved")

add(paper_id="P21",
    title="ColO-RAN: Developing Machine Learning-based xApps for Open RAN Closed-loop Control on Programmable Experimental Platforms",
    authors="NOT VERIFIED (Polese et al. group)", year="2022", venue="arXiv / IEEE TMC",
    link="https://arxiv.org/abs/2112.09559",
    open_source_code="likely (OpenRAN Gym lineage)", dataset="Colosseum-generated",
    testbed="Colosseum", oran_stack="srsRAN on Colosseum",
    ric_type="O-RAN SC Near-RT RIC", attack_types="none (control, not security)",
    feature_modalities="RAN KPMs", model="deep reinforcement learning xApps",
    adversarial_evaluation="no", external_validation="no", limitations="not a security study",
    relevance="MEDIUM - the platform citation our draft currently uses in place of a DATASET citation (see gate A1)",
    what_our_project_learns="this is a PLATFORM paper, and citing it as the provenance of D_A is the specific error gate A1 identifies",
    potential_gap="n/a", verification_status="TITLE AND URL ONLY - not retrieved")

add(paper_id="P22", title="Interpretable Anomaly-Based DDoS Detection in AI-RAN with XAI and LLMs",
    authors="NOT VERIFIED", year="2025", venue="arXiv", link="https://arxiv.org/abs/2507.21193",
    attack_types="DDoS", model="anomaly detection with XAI and an LLM",
    relevance="LOW-MEDIUM - related-work coverage",
    what_our_project_learns="current AI-RAN detection practice", limitations="not assessed",
    potential_gap="not assessed", verification_status="TITLE AND URL ONLY - not retrieved")

add(paper_id="P23", title="O-RAN E2SM-KPM DoS Detection Dataset and Evaluation Artifact",
    authors="Abdelhalim M.; Towhid M. S.; Shahriar N. (University of Regina)", year="2026",
    venue="Zenodo artifact, associated with a PST 2026 paper",
    link="https://doi.org/10.5281/zenodo.21198102 | https://github.com/Majdi-Abdelhalim/oran-dos-kpm-dataset",
    open_source_code="yes - MIT licence; oran-dos-kpm-dataset-v1.0.0.zip, 69.8 MB",
    dataset="O-RAN E2SM-KPM DoS detection dataset", ric_type="E2SM-KPM telemetry",
    attack_types="DoS",
    feature_modalities="E2SM-KPM KPIs (fields not stated on the record)",
    model="n/a (dataset plus evaluation artifact)", cross_deployment_evaluation="no",
    adversarial_evaluation="no", external_validation="n/a",
    limitations="the Zenodo record carries no description, so testbed, attack taxonomy and record counts are undocumented there",
    relevance="HIGH - the leading candidate for the Phase 13 INDEPENDENT external-validation corpus: different site, different team, MIT licence, and small enough to handle",
    what_our_project_learns="a third, genuinely independent O-RAN corpus may exist; the GitHub repository must be inspected to confirm feature overlap with our shared space",
    potential_gap="undocumented on Zenodo; needs direct inspection",
    verification_status="PARTIAL: Zenodo record retrieved but description empty; artefact NOT downloaded")

add(paper_id="P24",
    title="Cross-Layer Detection of Wireless Misbehavior Using 5G RAN Telemetry and Operational Metadata",
    authors="Ganiuly D.; Bolatbek N.; Smaiyl A.", year="2025", venue="arXiv",
    link="https://arxiv.org/abs/2511.21803", dataset="own testbed capture",
    testbed="controlled 5G Standalone testbed, commercial UE, SDR adversary",
    oran_stack="gNB (stack not stated)", ric_type="none stated",
    attack_types="power inflation; timing drift; off-grant uplink bursts",
    feature_modalities="PHY measurements, MAC scheduling decisions and gNB configuration metadata",
    model="rule and consistency-based cross-layer signatures, NOT machine learning",
    baseline_models="n/a", split_strategy="n/a", cross_deployment_evaluation="no",
    latency_evaluation="no", p95_latency="no", p99_latency="no", resource_evaluation="no",
    false_alert_evaluation="no", class_imbalance="n/a", attack_base_rate="no",
    adversarial_evaluation="no", external_validation="no",
    limitations="single controlled testbed; no false-positive rate; no operational scalability analysis",
    relevance="MEDIUM - an alternative, non-ML cross-layer detection design point",
    what_our_project_learns="cross-layer consistency signatures are a non-learned baseline family we had not considered, and are worth one Level-1/2 baseline in Phase 3",
    potential_gap="no FPR, no transfer, no deployability measurement",
    verification_status="PARTIAL: arXiv abstract page retrieved; full text NOT read")

add(paper_id="P25",
    title="From Description to Detection: LLM based Extendable O-RAN Compliant Blind DoS Detection in 5G and Beyond",
    authors="NOT VERIFIED", year="2025", venue="arXiv", link="https://arxiv.org/abs/2510.06530",
    ric_type="O-RAN compliant", attack_types="blind DoS", model="LLM-based",
    relevance="LOW-MEDIUM - related work",
    what_our_project_learns="LLM detectors are being proposed for near-RT roles, and their latency is a natural upper anchor on our Pareto plot",
    limitations="not assessed", potential_gap="not assessed",
    verification_status="TITLE AND URL ONLY - not retrieved")

out = pathlib.Path("docs/literature/LITERATURE_MATRIX.csv")
out.parent.mkdir(parents=True, exist_ok=True)
with out.open("w", newline="", encoding="utf-8") as fh:
    w = csv.DictWriter(fh, fieldnames=COLS)
    w.writeheader()
    w.writerows(R)
print("wrote %s : %d rows x %d cols" % (out, len(R), len(COLS)))

c = Counter(r["verification_status"].split(":")[0].split(" -")[0] for r in R)
print("verification status distribution:")
for k, v in c.most_common():
    print("  %2d  %s" % (v, k))
