#!/usr/bin/env python3
"""Generate every LaTeX table from processed results.

This closes defect B-002. The repository's stated non-negotiable is that no
number reaches the manuscript except by ``\\input`` from ``tables/generated/``.
Until now that was a statement of intent with no mechanism: the manuscript had
no ``\\input`` directive and nothing generated one. Given that the draft began
life with entirely synthetic values, a hand-copied number is indistinguishable
from a leftover placeholder, and this generator is what makes that distinction
structural rather than a matter of memory.

Every file emitted carries a provenance header naming the result file and the
git commit it was produced from.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import pandas as pd

OUT = Path("tables/generated")
RES = Path("results")

BS = "\\\\"          # a LaTeX row separator, as it appears in the output
NL = "\n"


def _commit() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def _provenance(source: str) -> str:
    return (f"% GENERATED by analysis/make_tables.py on {date.today().isoformat()}{NL}"
            f"% source: {source}{NL}"
            f"% commit: {_commit()}{NL}"
            f"% DO NOT EDIT. Edit the generator, then re-run `make tables`.{NL}")


def _write(name: str, rows: list[str], source: str, colspec: str, header: str):
    """Emit a COMPLETE tabular environment, not a fragment of rows.

    Why complete rather than just the rows: ``\\input`` inside a ``tabular``
    does not work in this TeX installation. The identical rows compile cleanly
    when inlined, and produce "Misplaced \\noalign" at the following
    ``\\bottomrule`` when pulled in by ``\\input``. Rather than fight that, the
    generator owns the whole environment and the manuscript inputs it at table
    level, which is a plain ``\\input`` in ordinary horizontal mode.

    This is the better design regardless of the bug: the column specification
    and the header row now live beside the code that decides how many columns
    there are, so the two cannot drift apart from the data.

    Line endings are forced to LF. Python's default text mode on Windows writes
    CRLF, which is not worth debugging inside a tabular twice.
    """
    OUT.mkdir(parents=True, exist_ok=True)
    body = NL.join(r.rstrip() for r in rows)
    text = (
        _provenance(source)
        + "\\begin{tabular}{" + colspec + "}" + NL
        + "\\toprule" + NL
        + header.rstrip() + NL
        + "\\midrule" + NL
        + body + NL
        + "\\bottomrule" + NL
        + "\\end{tabular}" + NL
    )
    with (OUT / f"{name}.tex").open("w", encoding="utf-8", newline=NL) as fh:
        fh.write(text)
    print(f"  wrote {OUT/name}.tex")


def _esc(s) -> str:
    return str(s).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


def _num(x, fmt=",.0f") -> str:
    """Thousands separated with a LaTeX thin space, which is the house style."""
    return format(x, fmt).replace(",", r"\,")


# ---------------------------------------------------------------------------
def table_corpora():
    src = RES / "EXP-002" / "statistics" / "provenance.json"
    if not src.exists():
        print("  skip corpora table"); return
    prov = json.loads(src.read_text(encoding="utf-8"))["corpora"]
    rows = [
        f"{_esc(layer)} & {_num(s['n_rows'])} & {s['n_features']} & "
        f"{s['attack_prevalence_pct']:.1f} & {_esc(s['group_key'])} & "
        f"{s['n_groups']} {BS}"
        for layer, s in prov.items()
    ]
    _write("corpora", rows, str(src), "lrrrlr",
           r"Layer & Rows & Features & Attack \% & Group key & Groups " + BS)


def table_leakage():
    src = RES / "EXP-002" / "processed" / "leakage_summary.csv"
    if not src.exists():
        print("  skip leakage table"); return
    df = pd.read_csv(src)
    for layer, g in df.groupby("layer"):
        g = g.sort_values("group_disjoint_f1_macro", ascending=False)
        rows = []
        for _, r in g.iterrows():
            ci = (f"[{r.delta_lo:+.3f}, {r.delta_hi:+.3f}]"
                  if pd.notna(r.get("delta_lo")) else "--")
            star = r"$^{\ast}$" if r.get("delta_excludes_zero") is True else ""
            rows.append(
                f"{_esc(r.model)} & {r['random_f1_macro']:.3f} & "
                f"{r['group_disjoint_f1_macro']:.3f} & "
                f"{r['leakage_delta']:+.3f}{star} & {ci} {BS}")
        _write(f"leakage_{layer}", rows, str(src), "lcccc",
               r"Model & Random & Run-disjoint & $\Delta$ & 95\,\% CI " + BS)


def table_alert_burden():
    src = RES / "EXP-004" / "processed" / "alert_burden_radio.csv"
    if not src.exists():
        print("  skip alert-burden table"); return
    df = pd.read_csv(src, index_col=0)
    rows = [
        f"{_esc(m)} & {r.f1_macro:.3f} & {r.corpus_precision:.3f} & "
        f"{r.recall:.3f} & {r.fpr:.3f} & {_num(r.alerts_h)} & {r.ppv:.3f} {BS}"
        for m, r in df.iterrows()
    ]
    _write("alert_burden", rows, str(src), "lcccccc",
           r"Model & Macro-$F_1$ & Corpus $P$ & Recall & FPR & Alerts/h & PPV " + BS)


def table_latency():
    src = RES / "EXP-005" / "processed" / "budget_sweep_radio.csv"
    if not src.exists():
        print("  skip latency table"); return
    df = pd.read_csv(src).sort_values("p99")
    rows = []
    for _, r in df.iterrows():
        mb = r.get("min_conforming_budget_ms")
        mb_s = f"{mb:.0f}" if pd.notna(mb) else r"$>$1000"
        rows.append(f"{_esc(r.model)} & {r.p50:.2f} & {r.p95:.2f} & {r.p99:.2f} & "
                    f"{r['p99.9']:.2f} & {mb_s} {BS}")
    _write("latency_budget", rows, str(src), "lccccc",
           r"Model & $p_{50}$ & $p_{95}$ & $p_{99}$ & $p_{99.9}$ & Min.\ budget " + BS)


def table_ppv_crossings():
    src = RES / "EXP-004" / "processed" / "ppv_crossings_radio.csv"
    if not src.exists():
        print("  skip ppv-crossings table"); return
    df = pd.read_csv(src)
    rows = []
    for _, r in df.iterrows():
        if pd.isna(r.tau_required):
            rows.append(f"{_esc(r.model)} & {r.ppv_target:.2f} & "
                        f"\\textit{{unreachable}} & -- & -- {BS}")
        else:
            rows.append(f"{_esc(r.model)} & {r.ppv_target:.2f} & {r.tau_required:.2f} & "
                        f"{r.recall_at_tau:.3f} & {_num(r.alerts_per_hour)} {BS}")
    _write("ppv_crossings", rows, str(src), "lcccc",
           r"Model & PPV target & $\tau$ required & Recall & Alerts/h " + BS)


def main() -> int:
    print("generating LaTeX tables...")
    table_corpora()
    table_leakage()
    table_alert_burden()
    table_latency()
    table_ppv_crossings()
    print("done. \\input these at TABLE level from paper/ -- never retype a value,")
    print("and never \\input them inside a tabular.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
