#!/usr/bin/env python3
"""Generate every LaTeX table from processed results.

This closes defect B-002. The repository's stated non-negotiable is that no
number reaches the manuscript except by ``\\input`` from ``tables/generated/``.
Until now that was a statement of intent with no mechanism: the manuscript had
no ``\\input`` directive and nothing generated one. Given that the draft began
life with entirely synthetic values, a hand-copied number is indistinguishable
from a leftover placeholder, and this generator is what makes that distinction
structural rather than a matter of memory.

Every file emitted carries a provenance header naming the result file and the
git commit it was produced from.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import pandas as pd

OUT = Path("tables/generated")
RES = Path("results")

BS = "\\\\"          # a LaTeX row separator, as it appears in the output
NL = "\n"


def _commit() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def _provenance(source: str) -> str:
    return (f"% GENERATED by analysis/make_tables.py on {date.today().isoformat()}{NL}"
            f"% source: {source}{NL}"
            f"% commit: {_commit()}{NL}"
            f"% DO NOT EDIT. Edit the generator, then re-run `make tables`.{NL}")


def _write(name: str, rows: list[str], source: str, colspec: str, header: str):
    """Emit a COMPLETE tabular environment, not a fragment of rows.

    Why complete rather than just the rows: ``\\input`` inside a ``tabular``
    does not work in this TeX installation. The identical rows compile cleanly
    when inlined, and produce "Misplaced \\noalign" at the following
    ``\\bottomrule`` when pulled in by ``\\input``. Rather than fight that, the
    generator owns the whole environment and the manuscript inputs it at table
    level, which is a plain ``\\input`` in ordinary horizontal mode.

    This is the better design regardless of the bug: the column specification
    and the header row now live beside the code that decides how many columns
    there are, so the two cannot drift apart from the data.

    Line endings are forced to LF. Python's default text mode on Windows writes
    CRLF, which is not worth debugging inside a tabular twice.
    """
    OUT.mkdir(parents=True, exist_ok=True)
    body = NL.join(r.rstrip() for r in rows)
    text = (
        _provenance(source)
        + "\\begin{tabular}{" + colspec + "}" + NL
        + "\\toprule" + NL
        + header.rstrip() + NL
        + "\\midrule" + NL
        + body + NL
        + "\\bottomrule" + NL
        + "\\end{tabular}" + NL
    )
    with (OUT / f"{name}.tex").open("w", encoding="utf-8", newline=NL) as fh:
        fh.write(text)
    print(f"  wrote {OUT/name}.tex")


def _esc(s) -> str:
    return str(s).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


def _num(x, fmt=",.0f") -> str:
    """Thousands separated with a LaTeX thin space, which is the house style."""
    return format(x, fmt).replace(",", r"\,")


# ---------------------------------------------------------------------------
def table_corpora():
    src = RES / "EXP-002" / "statistics" / "provenance.json"
    if not src.exists():
        print("  skip corpora table"); return
    prov = json.loads(src.read_text(encoding="utf-8"))["corpora"]
    rows = [
        f"{_esc(layer)} & {_num(s['n_rows'])} & {s['n_features']} & "
        f"{s['attack_prevalence_pct']:.1f} & {_esc(s['group_key'])} & "
        f"{s['n_groups']} {BS}"
        for layer, s in prov.items()
    ]
    _write("corpora", rows, str(src), "lrrrlr",
           r"Layer & Rows & Features & Attack \% & Group key & Groups " + BS)


def table_leakage():
    src = RES / "EXP-002" / "processed" / "leakage_summary.csv"
    if not src.exists():
        print("  skip leakage table"); return
    df = pd.read_csv(src)
    for layer, g in df.groupby("layer"):
        g = g.sort_values("group_disjoint_f1_macro", ascending=False)
        rows = []
        for _, r in g.iterrows():
            ci = (f"[{r.delta_lo:+.3f}, {r.delta_hi:+.3f}]"
                  if pd.notna(r.get("delta_lo")) else "--")
            star = r"$^{\ast}$" if r.get("delta_excludes_zero") is True else ""
            rows.append(
                f"{_esc(r.model)} & {r['random_f1_macro']:.3f} & "
                f"{r['group_disjoint_f1_macro']:.3f} & "
                f"{r['leakage_delta']:+.3f}{star} & {ci} {BS}")
        _write(f"leakage_{layer}", rows, str(src), "lcccc",
               r"Model & Random & Run-disjoint & $\Delta$ & 95\,\% CI " + BS)


def table_alert_burden():
    src = RES / "EXP-004" / "processed" / "alert_burden_radio.csv"
    if not src.exists():
        print("  skip alert-burden table"); return
    df = pd.read_csv(src, index_col=0)
    rows = [
        f"{_esc(m)} & {r.f1_macro:.3f} & {r.corpus_precision:.3f} & "
        f"{r.recall:.3f} & {r.fpr:.3f} & {_num(r.alerts_h)} & {r.ppv:.3f} {BS}"
        for m, r in df.iterrows()
    ]
    _write("alert_burden", rows, str(src), "lcccccc",
           r"Model & Macro-$F_1$ & Corpus $P$ & Recall & FPR & Alerts/h & PPV " + BS)


def table_latency():
    src = RES / "EXP-005" / "processed" / "budget_sweep_radio.csv"
    if not src.exists():
        print("  skip latency table"); return
    df = pd.read_csv(src).sort_values("p99")
    rows = []
    for _, r in df.iterrows():
        mb = r.get("min_conforming_budget_ms")
        mb_s = f"{mb:.0f}" if pd.notna(mb) else r"$>$1000"
        rows.append(f"{_esc(r.model)} & {r.p50:.2f} & {r.p95:.2f} & {r.p99:.2f} & "
                    f"{r['p99.9']:.2f} & {mb_s} {BS}")
    _write("latency_budget", rows, str(src), "lccccc",
           r"Model & $p_{50}$ & $p_{95}$ & $p_{99}$ & $p_{99.9}$ & Min.\ budget " + BS)


def table_ppv_crossings():
    src = RES / "EXP-004" / "processed" / "ppv_crossings_radio.csv"
    if not src.exists():
        print("  skip ppv-crossings table"); return
    df = pd.read_csv(src)
    rows = []
    for _, r in df.iterrows():
        if pd.isna(r.tau_required):
            rows.append(f"{_esc(r.model)} & {r.ppv_target:.2f} & "
                        f"\\textit{{unreachable}} & -- & -- {BS}")
        else:
            rows.append(f"{_esc(r.model)} & {r.ppv_target:.2f} & {r.tau_required:.2f} & "
                        f"{r.recall_at_tau:.3f} & {_num(r.alerts_per_hour)} {BS}")
    _write("ppv_crossings", rows, str(src), "lcccc",
           r"Model & PPV target & $\tau$ required & Recall & Alerts/h " + BS)


def table_shared_space():
    """The shared feature space, from the committed mapping.

    Replaces the manuscript's hand-written ``tab:features``, which claimed 24
    packet-level features in four families -- including a Timing family of seven
    members with a measured covariate shift, on a corpus that publishes no
    inter-arrival statistics at all.
    """
    import yaml
    src = Path("configs/features/shared_space.yaml")
    if not src.exists():
        print("  skip shared-space table"); return
    spec = yaml.safe_load(src.read_text(encoding="utf-8"))
    rows = []
    for concept, m in spec["base_numeric"].items():
        rows.append(f"{_esc(concept)} & {_esc(m['d_a'])} & {_esc(m['d_b'])} & "
                    f"base {BS}")
    p = spec["base_categorical"]["proto"]
    rows.append(f"proto & {_esc(p['d_a'])} & {_esc(p['d_b'])} & "
                f"one-hot ({len(p['levels'])}) {BS}")
    for concept, expr in spec["derived"].items():
        rows.append(f"{_esc(concept)} & \\multicolumn{{2}}{{c}}{{{_esc(expr)}}} & "
                    f"derived {BS}")
    _write("shared_space", rows, str(src), "llll",
           r"Concept & \DA{} (Zeek) & \DB{} (Argus) & Role " + BS)


def table_transfer():
    """Cross-deployment transfer. Replaces the fully synthetic ``tab:cross``."""
    for direction, label in (("a_to_b", "d_a_to_d_b"), ("b_to_a", "d_b_to_d_a")):
        src = RES / "EXP-026" / "processed" / f"transfer_summary__{direction}.csv"
        if not src.exists():
            print(f"  skip transfer table ({direction})"); continue
        df = pd.read_csv(src)
        order = ["logreg", "tree", "rf", "xgboost", "hgb", "mlp",
                 "stratified", "majority"]
        df["_o"] = df.model.map({m: i for i, m in enumerate(order)})
        df = df.sort_values("_o")
        rows = []
        for _, r in df.iterrows():
            ci = (f"[{r.delta_lo:+.3f}, {r.delta_hi:+.3f}]"
                  if pd.notna(r.get("delta_lo")) else "--")
            star = (r"$^{\ast}$" if r.get("significant") is True
                    or str(r.get("significant")).lower() == "true" else "")
            name = _esc(r.model)
            if r.model in ("majority", "stratified"):
                name = r"\textit{" + name + "}"     # the floor, not a competitor
            rows.append(f"{name} & {r.source_f1:.3f} & {r.target_f1:.3f} & "
                        f"{r.delta_f1:+.3f}{star} & {ci} & "
                        f"{r.tgt_pr_auc:.3f} {BS}")
        _write(f"transfer_{label}", rows, str(src), "lccccc",
               r"Model & Source held-out & Target & $\Delta_{F_1}$ & "
               r"95\,\% CI & Target PR-AUC " + BS)


def table_per_category():
    """Per-category detection on the target, which macro-F1 hides.

    Replaces the manuscript's synthetic confusion matrix. A single aggregate
    number cannot show that one architecture keeps 98% benign specificity while
    another calls 88% of benign traffic an attack, nor that categories absent
    from the training corpus are essentially undetected.
    """
    for direction, label in (("a_to_b", "d_b"), ("b_to_a", "d_a")):
        src = RES / "EXP-026" / "processed" / f"per_category_recall__{direction}.csv"
        if not src.exists():
            print(f"  skip per-category table ({direction})"); continue
        df = pd.read_csv(src)
        cats = [c for c in df.columns
                if not c.endswith("__n")
                and c not in ("direction", "model", "split_seed")]
        g = df.groupby("model")[cats].mean()
        order = [m for m in ["logreg", "tree", "rf", "xgboost", "hgb", "mlp"]
                 if m in g.index]
        # benign first (it is specificity, not recall), then the attack classes
        cols = (["benign"] if "benign" in cats else []) + \
               sorted(c for c in cats if c != "benign")
        rows = []
        for m in order:
            vals = " & ".join(f"{g.loc[m, c]:.3f}" for c in cols)
            rows.append(f"{_esc(m)} & {vals} {BS}")
        head = " & ".join(_esc(c) for c in cols)
        _write(f"per_category_{label}", rows, str(src),
               "l" + "c" * len(cols),
               f"Model & {head} " + BS)


def table_prevalence():
    """PPV against the base rate, pooled. The '6x' clause died here (D-018)."""
    src = RES / "EXP-027" / "processed" / "ppv_spread_vs_prevalence.csv"
    if not src.exists():
        print("  skip prevalence table"); return
    df = pd.read_csv(src)
    for surface, g in df.groupby("surface"):
        g = g.sort_values("pi")
        rows = [f"{r.pi:g} & {r.ppv_min:.4f} & {r.ppv_max:.4f} & "
                f"{r.ppv_ratio:.2f} & {r.corpus_precision_range:.4f} & "
                f"{r.collapse_factor:,.0f} {BS}".replace(",", r"\,")
                for _, r in g.iterrows()]
        _write(f"prevalence_{surface}", rows, str(src), "rccccr",
               r"$\pi$ & PPV min & PPV max & Spread & Corpus-prec.\ range & "
               r"Collapse $\times$ " + BS)


def table_estimator_bug():
    """B-E. Three estimators of one quantity, so the artefact stays visible."""
    src = RES / "EXP-027" / "processed" / "estimator_comparison.csv"
    if not src.exists():
        print("  skip estimator table"); return
    df = pd.read_csv(src)
    df = df[~df.model.isin(["majority", "stratified"])].sort_values(
        "ppv_mean_of_folds", ascending=False)
    rows = [f"{_esc(r.model)} & {int(r.n_folds_ppv_equals_1)} & "
            f"{r.ppv_pooled:.4f} & {r.ppv_median_of_folds:.4f} & "
            f"{r.ppv_mean_of_folds:.4f} {BS}"
            for _, r in df.iterrows()]
    _write("estimator_bug", rows, str(src), "lrccc",
           r"Model & Folds with FPR $=0$ & Pooled & Median & Mean " + BS)


def table_extraction():
    """Extraction cost by implementation (EXP-030)."""
    src = RES / "EXP-030" / "processed" / "extraction_speedup.csv"
    if not src.exists():
        print("  skip extraction table"); return
    df = pd.read_csv(src).sort_values("pkts_per_flow", ascending=False)
    rows = [f"{int(r.n_flows_declared):,} & {int(r.pkts_per_flow)} & "
            f"{r.us_per_pkt_reference:.1f} & {r.us_per_pkt_vectorised:.1f} & "
            f"{r.ms_per_flow_vectorised:.3f} & {r.speedup:.1f} {BS}".replace(
                ",", r"\,")
            for _, r in df.iterrows()]
    _write("extraction", rows, str(src), "rrcccc",
           r"Flows & Pkts/flow & Ref.\ \si{\micro\second}/pkt & "
           r"Vec.\ \si{\micro\second}/pkt & Vec.\ ms/flow & Speed-up " + BS)


def main() -> int:
    print("generating LaTeX tables...")
    table_corpora()
    table_leakage()
    table_alert_burden()
    table_latency()
    table_ppv_crossings()
    table_shared_space()
    table_transfer()
    table_per_category()
    table_prevalence()
    table_estimator_bug()
    table_extraction()
    print("done. \\input these at TABLE level from paper/ -- never retype a value,")
    print("and never \\input them inside a tabular.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
