#!/usr/bin/env python3
"""Generate every LaTeX table body from processed results.

This closes defect B-002. The repository's stated non-negotiable is that no
number reaches the manuscript except by ``\\input`` from ``tables/generated/``.
Until now that was a statement of intent with no mechanism: the manuscript had
no ``\\input`` directive and nothing generated one. Given that the draft began
life with entirely synthetic values, a hand-copied number is indistinguishable
from a leftover placeholder, and this generator is what makes that distinction
structural rather than a matter of memory.

Every table body emitted here carries a provenance comment naming the result
file and the git commit it was generated from.
"""
from __future__ import annotations

import subprocess
import sys
from datetime import date
from pathlib import Path

import pandas as pd

OUT = Path("tables/generated")
RES = Path("results")


def _commit() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def _header(source: str) -> str:
    return (f"% GENERATED by analysis/make_tables.py on {date.today().isoformat()}\n"
            f"% source: {source}\n"
            f"% commit: {_commit()}\n"
            f"% DO NOT EDIT. Edit the generator, re-run `make tables`.\n")


def _write(name: str, body: str, source: str):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.tex").write_text(_header(source) + body, encoding="utf-8")
    print(f"  wrote {OUT/name}.tex")


def _esc(s) -> str:
    return str(s).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


# ---------------------------------------------------------------------------
def table_leakage():
    src = RES / "EXP-002" / "processed" / "leakage_summary.csv"
    if not src.exists():
        print("  skip leakage table"); return
    df = pd.read_csv(src)
    for layer, g in df.groupby("layer"):
        g = g.sort_values("group_disjoint_f1_macro", ascending=False)
        rows = []
        for _, r in g.iterrows():
            ci = ""
            if pd.notna(r.get("delta_lo")):
                ci = f"[{r.delta_lo:+.3f}, {r.delta_hi:+.3f}]"
            star = r"$^{\ast}$" if r.get("delta_excludes_zero") is True else ""
            rows.append(
                f"{_esc(r.model)} & {r['random_f1_macro']:.3f} & "
                f"{r['group_disjoint_f1_macro']:.3f} & "
                f"{r['leakage_delta']:+.3f}{star} & {ci} \\\\")
        _write(f"leakage_{layer}", "\n".join(rows) + "\n", str(src))


def table_alert_burden():
    src = RES / "EXP-004" / "processed" / "alert_burden_radio.csv"
    if not src.exists():
        print("  skip alert-burden table"); return
    df = pd.read_csv(src, index_col=0)
    rows = []
    for m, r in df.iterrows():
        rows.append(
            f"{_esc(m)} & {r.f1_macro:.3f} & {r.corpus_precision:.3f} & "
            f"{r.recall:.3f} & {r.fpr:.4f} & "
            f"{r.alerts_h:,.0f} & {r.ppv:.4f} \\\\".replace(",", r"\,"))
    _write("alert_burden", "\n".join(rows) + "\n", str(src))


def table_latency():
    src = RES / "EXP-005" / "processed" / "budget_sweep_radio.csv"
    if not src.exists():
        print("  skip latency table"); return
    df = pd.read_csv(src).sort_values("p99")
    rows = []
    for _, r in df.iterrows():
        mb = r.get("min_conforming_budget_ms")
        mb_s = f"{mb:.0f}" if pd.notna(mb) else r"$>$1000"
        rows.append(f"{_esc(r.model)} & {r.p50:.2f} & {r.p95:.2f} & {r.p99:.2f} & "
                    f"{r['p99.9']:.2f} & {mb_s} \\\\")
    _write("latency_budget", "\n".join(rows) + "\n", str(src))


def table_corpora():
    """Table I: what each corpus actually is, measured not quoted."""
    import json
    rows = []
    p = RES / "EXP-002" / "statistics" / "provenance.json"
    if p.exists():
        prov = json.loads(p.read_text(encoding="utf-8"))["corpora"]
        for layer, s in prov.items():
            rows.append(
                f"{_esc(layer)} & {s['n_rows']:,} & {s['n_features']} & "
                f"{s['attack_prevalence_pct']:.1f} & {_esc(s['group_key'])} & "
                f"{s['n_groups']} \\\\".replace(",", r"\,"))
    if rows:
        _write("corpora", "\n".join(rows) + "\n", str(p))
    else:
        print("  skip corpora table")


def table_ppv_crossings():
    src = RES / "EXP-004" / "processed" / "ppv_crossings_radio.csv"
    if not src.exists():
        print("  skip ppv-crossings table"); return
    df = pd.read_csv(src)
    rows = []
    for _, r in df.iterrows():
        if pd.isna(r.tau_required):
            rows.append(f"{_esc(r.model)} & {r.ppv_target:.2f} & "
                        f"\\textit{{unreachable}} & -- & -- \\\\")
        else:
            rows.append(f"{_esc(r.model)} & {r.ppv_target:.2f} & {r.tau_required:.2f} & "
                        f"{r.recall_at_tau:.3f} & {r.alerts_per_hour:,.0f} \\\\"
                        .replace(",", r"\,"))
    _write("ppv_crossings", "\n".join(rows) + "\n", str(src))


def main() -> int:
    print("generating LaTeX table bodies...")
    table_corpora()
    table_leakage()
    table_alert_burden()
    table_latency()
    table_ppv_crossings()
    print("done. \\input these from paper/main.tex -- never retype a value.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
